version: '2'
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isread -U admin -d metastore_db"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks: 
      - dataeng-data-platform

  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    build: .
    ports:
      - 9083:9083
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HIVE_CUSTOM_CONF_DIR: /opt/hive/conf
    volumes:
      - ./hive-config:/opt/hive/conf
      - ./hadoop-libs/hadoop-aws-3.1.0.jar:/opt/hive/lib/hadoop-aws-3.1.0.jar
      - ./hadoop-libs/aws-java-sdk-bundle-1.11.271.jar:/opt/hive/lib/aws-java-sdk-bundle-1.11.271.jar
    depends_on:
      - postgres
    networks:
      - dataeng-data-platform

networks:
  dataeng-data-platform:
    external: true