version: '3'
services:
  spark-master:
    hostname: spark-master
    container_name: spark-master
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark-config/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
      - ./jars/aws-java-sdk-bundle-1.12.367.jar:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.367.jar
      - ./jars/hadoop-aws-3.3.6.jar:/opt/bitnami/spark/jars/hadoop-aws-3.3.6.jar
      - ./jars/hudi-spark3.4-bundle_2.12-0.14.1.jar:/opt/bitnami/spark/jars/hudi-spark3.4-bundle_2.12-0.14.1.jar
      - ./jars/delta-core_2.12-2.4.0.jar:/opt/bitnami/spark/jars/delta-core_2.12-2.4.0.jar
      - ./jars/delta-storage-2.4.0.jar:/opt/bitnami/spark/jars/delta-storage-2.4.0.jar
      - ./jars/antlr4-runtime-4.9.3.jar:/opt/bitnami/spark/jars/antlr4-runtime-4.9.3.jar
      - ./jars/wildfly-openssl-1.1.3.Final.jar:/opt/bitnami/spark/jars/wildfly-openssl-1.1.3.Final.jar

    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - dataeng-data-platform

  spark-worker-1:
    hostname: spark-worker-1
    container_name: spark-worker-1
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - dataeng-data-platform

  spark-worker-2:
    hostname: spark-worker-2
    container_name: spark-worker-2
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - dataeng-data-platform

    

networks:
  dataeng-data-platform:
    external: true