version: '3'
services:
  minIO:
    container_name: 'minIO'
    image: 'minio/minio:RELEASE.2024-03-03T17-50-39Z' 
    environment:
      MINIO_ROOT_USER: 'minIOuser' 
      MINIO_ROOT_PASSWORD: 'minIOpass'
    ports:
      - "9000:9000"
      - '9090:9090'
    volumes:
      - ~/my-repos/datalake:/data
    networks:
      - dataeng-data-platform
    command: server /data --console-address ":9090"
  createbucket:
    hostname: createbucket
    container_name: createbucket
    image: minio/mc:RELEASE.2024-01-13T08-44-48Z
    depends_on:
     - minIO
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minIO:9000 minIOuser minIOpass;
      /usr/bin/mc mb myminio/lakehouse;
      /usr/bin/mc anonymous set public myminio/lakehouse;
      "
    networks:
      - dataeng-data-platform
networks:
  dataeng-data-platform:
    external: true