version: '3'
services:
  minIO:
    container_name: 'minIO'
    image: 'minio/minio:RELEASE.2024-03-03T17-50-39Z' 
    environment:
      MINIO_ROOT_USER: 'minIOuser' 
      MINIO_ROOT_PASSWORD: 'minIOpass'
    ports:
      - "9000:9000"
      - '9090:9090'
    volumes:
      - ~/my-repos/datalake:/data
    networks:
      - dataeng-data-platform
    command: server /data --console-address ":9090"

networks:
  dataeng-data-platform:
    external: true